Pull_Bear/Pull_Bear.MVC/Areas/Manage/Controllers/OrderController.cs
using Microsoft.AspNetCore.Mvc;
using Pull_Bear.Core.Enums;
using Pull_Bear.Service.Interfaces;
using Pull_Bear.Service.ViewModels;
using Pull_Bear.Service.ViewModels.OrderVMs;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Pull_Bear.MVC.Areas.Manage.Controllers
{
    [Area("Manage")]
    public class OrderController : Controller
    {
        private readonly IOrderService _orderService;

        public OrderController(IOrderService orderService)
        {
            _orderService = orderService;
        }

        public async Task<IActionResult> Index(int? ordertype, int select, int page = 1)
        {
            IQueryable<OrderListVM> orderListVM = await _orderService.GetAllOrders(ordertype, select);

            if (select <= 0)
            {
                select = 5;
            }

            ViewBag.Select = select;
            ViewBag.Page = page;

            return View(PaginationList<OrderListVM>.Create(orderListVM, page, select));
        }

        [HttpGet]
        public async Task<IActionResult> Update(int? id)
        {
            return View(await _orderService.GetOrderById(id));
        }

        [HttpPost]
        public async Task<IActionResult> Update(int? id, OrderStatus orderStatus)
        {
            await _orderService.UpdateOrder(id, orderStatus);

            return RedirectToAction("Index");
        }
    }
}

Pull_Bear/Pull_Bear.MVC/Controllers/BasketController.cs
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using Pull_Bear.Core;
using Pull_Bear.Core.Models;
using Pull_Bear.Service.ViewModels.BasketVMs;
using Pull_Bear.Service.ViewModels.ProductVMs;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Pull_Bear.MVC.Controllers 
{
    public class BasketController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        private readonly UserManager<AppUser> _userManager;
        private readonly IMapper _mapper;

        public BasketController(UserManager<AppUser> userManager, IUnitOfWork unitOfWork, IMapper mapper)
        {
            _userManager = userManager;
            _unitOfWork = unitOfWork;
            _mapper = mapper;
        }

        public async Task<IActionResult> Index()
        {
            string basket = HttpContext.Request.Cookies["basket"];

            List<BasketVM> basketVMs = null;

            if (!string.IsNullOrWhiteSpace(basket))
            {
                basketVMs = JsonConvert.DeserializeObject<List<BasketVM>>(basket);
            }
            else
            {
                basketVMs = new List<BasketVM>();
            }

            return View(new BasketIndexVM() { BasketVM = await _getBasketItemAsync(basketVMs), Products = _mapper.Map<List<ProductListVM>>(await _unitOfWork.ProductRepository.GetAllAsync("ProductColorSizes", "ProductColorSizes.Color", "ProductColorSizes.Size", "ProductImages", "BodyFit", "Gender", "Category")) });
        }

        public async Task<IActionResult> AddToBasket(AddToBasketVM addToBasketVM)
        {
            if (addToBasketVM.ColorId <= 0 || addToBasketVM.SizeId <= 0 || addToBasketVM.ProductId <= 0) return BadRequest();

            Product dbProduct = await _unitOfWork.ProductRepository.GetAsync(x => x.Id == addToBasketVM.ProductId, "ProductColorSizes", "ProductColorSizes.Color", "ProductColorSizes.Size", "ProductImages", "BodyFit", "Gender", "Category");

            ProductColorSize productColorSize = await _unitOfWork.ProductColorSizeRepository.GetAsync(x => x.ProductId == addToBasketVM.ProductId && x.ColorId == addToBasketVM.ColorId && x.SizeId == addToBasketVM.SizeId, "Product", "Size", "Color");

            if (dbProduct == null) return NotFound();

            if (dbProduct.Count <= 0) return BadRequest();

            if (productColorSize != null)
            {
                productColorSize.Count--;
            }

            dbProduct.Count--;

            await _unitOfWork.CommitAsync();

            string basket = HttpContext.Request.Cookies["basket"];

            List<BasketVM> basketVMs = null;

            if (!string.IsNullOrWhiteSpace(basket))
            {
                basketVMs = JsonConvert.DeserializeObject<List<BasketVM>>(basket);
            }
            else
            {
                basketVMs = new List<BasketVM>();
            }

            if (basketVMs.Exists(bvm => bvm.ProductId == addToBasketVM.ProductId && bvm.ColorId == addToBasketVM.ColorId && bvm.SizeId == addToBasketVM.SizeId))
            {
                basketVMs.Find(bvm => bvm.ProductId == addToBasketVM.ProductId && bvm.ColorId == addToBasketVM.ColorId && bvm.SizeId == addToBasketVM.SizeId).Count++;
            }
            else
            {
                ProductColorSize pcs = await _unitOfWork.ProductColorSizeRepository.GetAsync(x => x.ProductId == addToBasketVM.ProductId && x.ColorId == addToBasketVM.ColorId && x.SizeId == addToBasketVM.SizeId, "Product", "Size", "Color");

                if (pcs != null)
                {
                    BasketVM basketVM = new BasketVM
                    {
                        ProductId = addToBasketVM.ProductId,
                        SizeId = addToBasketVM.SizeId,
                        ColorId = addToBasketVM.ColorId,
                        ProductImage = dbProduct.ProductImage,
                        ColorHexCode = _unitOfWork.ColorRepository.GetAsync(x => x.Id == addToBasketVM.ColorId).Result.HexCode,
                        ColorName = _unitOfWork.ColorRepository.GetAsync(x => x.Id == addToBasketVM.ColorId).Result.Name,
                        Name = dbProduct.Name,
                        Price = dbProduct.DiscountPrice,
                        SizeName = _unitOfWork.SizeRepository.GetAsync(x => x.Id == addToBasketVM.SizeId).Result.Name,
                        Seria = dbProduct.Seria,
                        ItemsCount = pcs.Count,
                        Count = 1
                    };

                    basketVMs.Add(basketVM);
                }
            }

            if (User.Identity.IsAuthenticated)
            {
                AppUser appUser = await _userManager.Users.Include(u => u.Baskets).FirstOrDefaultAsync(u => u.UserName == User.Identity.Name);

                if (appUser.Baskets != null && appUser.Baskets.Count() > 0)
                {
                    Basket dbBasket = appUser.Baskets.FirstOrDefault(b => b.ProductId == addToBasketVM.ProductId && b.ColorId == addToBasketVM.ColorId && b.SizeId == addToBasketVM.SizeId);

                    if (dbBasket != null)
                    {
                        dbBasket.Count += 1;
                    }
                    else
                    {
                        ProductColorSize pcs = await _unitOfWork.ProductColorSizeRepository.GetAsync(x => x.ProductId == addToBasketVM.ProductId && x.ColorId == addToBasketVM.ColorId && x.SizeId == addToBasketVM.SizeId, "Product", "Size", "Color");

                        if (pcs != null)
                        {
                            Basket newBasket = new Basket
                            {
                                ProductId = addToBasketVM.ProductId,
                                SizeId = addToBasketVM.SizeId,
                                ColorId = addToBasketVM.ColorId,
                                Name = dbProduct.Name,
                                Price = dbProduct.DiscountPrice,
                                Count = 1
                            };

                            appUser.Baskets.Add(newBasket);
                        }
                    }
                }
                else
                {
                    ProductColorSize pcs = await _unitOfWork.ProductColorSizeRepository.GetAsync(x => x.ProductId == addToBasketVM.ProductId && x.ColorId == addToBasketVM.ColorId && x.SizeId == addToBasketVM.SizeId, "Product", "Size", "Color");

                    if (pcs != null)
                    {
                        List<Basket> baskets = new List<Basket>
                        {
                            new Basket
                            {
                                ProductId = addToBasketVM.ProductId,
                                SizeId = addToBasketVM.SizeId,
                                ColorId = addToBasketVM.ColorId,
                                Name = dbProduct.Name,
                                Price = dbProduct.DiscountPrice,
                                Count = 1
                            }
                        };

                        appUser.Baskets = baskets;
                    }
                }

                await _unitOfWork.CommitAsync();
            }

            basket = JsonConvert.SerializeObject(basketVMs);

            HttpContext.Response.Cookies.Append("basket", basket);

            return PartialView("_BasketPartial", await _getBasketItemAsync(basketVMs));
        }

        public async Task<IActionResult> DeleteFromBasket(DeleteFromBasketVM deleteFromBasketVM)
        {
            if (deleteFromBasketVM == null) return BadRequest();

            if (await _unitOfWork.ProductColorSizeRepository.GetAsync(x => x.ProductId == deleteFromBasketVM.ProductId && x.ColorId == deleteFromBasketVM.ColorId && x.SizeId == deleteFromBasketVM.SizeId && !x.Product.IsDeleted, "Product", "Color", "Size") == null) return NotFound();

            ProductColorSize pcs = await _unitOfWork.ProductColorSizeRepository.GetAsync(x => x.ProductId == deleteFromBasketVM.ProductId && x.ColorId == deleteFromBasketVM.ColorId && x.SizeId == deleteFromBasketVM.SizeId, "Product", "Size", "Color");

            pcs.Count += deleteFromBasketVM.CountInBasket;

            Product product = await _unitOfWork.ProductRepository.GetAsync(x => x.Id == deleteFromBasketVM.ProductId);

            product.Count += deleteFromBasketVM.CountInBasket;

            await _unitOfWork.CommitAsync();

            string basket = HttpContext.Request.Cookies["basket"];

            if (string.IsNullOrWhiteSpace(basket)) return BadRequest();

            List<BasketVM> basketVMs = JsonConvert.DeserializeObject<List<BasketVM>>(basket);

            BasketVM basketVM = basketVMs.Find(b => b.ProductId == deleteFromBasketVM.ProductId && b.ColorId == deleteFromBasketVM.ColorId && b.SizeId == deleteFromBasketVM.SizeId);

            if (basketVM == null) return NotFound();

            if (User.Identity.IsAuthenticated)
            {
                AppUser appUser = await _userManager.Users.Include(u => u.Baskets).FirstOrDefaultAsync(u => u.UserName == User.Identity.Name);

                if (appUser.Baskets != null && appUser.Baskets.Count() > 0)
                {
                    Basket dbBasket = appUser.Baskets.FirstOrDefault(b => b.ProductId == deleteFromBasketVM.ProductId && b.ColorId == deleteFromBasketVM.ColorId && b.SizeId == deleteFromBasketVM.SizeId);

                    if (dbBasket != null)
                    {
                        _unitOfWork.BasketRepository.Remove(dbBasket);

                        await _unitOfWork.CommitAsync();
                    }
                }
            }

            basketVMs.Remove(basketVM);

            basket = JsonConvert.SerializeObject(basketVMs);

Pull_Bear/Pull_Bear.MVC/Controllers/OrderController.cs
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Pull_Bear.Service.Interfaces;
using Pull_Bear.Service.ViewModels.AddressVMs;
using Pull_Bear.Service.ViewModels.AppUserVMs;
using Pull_Bear.Service.ViewModels.BasketVMs;
using Pull_Bear.Service.ViewModels.CardVMs;
using Pull_Bear.Service.ViewModels.OrderVMs;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;

namespace Pull_Bear.MVC.Controllers
{
    public class OrderController : Controller
    {
        private readonly IOrderService _orderService;
        private readonly IMapper _mapper; 

        public OrderController(IOrderService orderService, IMapper mapper)
        {
            _orderService = orderService;
            _mapper = mapper;
        }

        [Authorize(Roles = "Member")]
        public async Task<IActionResult> Index()
        {
            return View(await _orderService.GetOrders());
        }

        public async Task<IActionResult> SortOrders(string sortvalue)
        {
            return PartialView("_OrdersPartial", await _orderService.SortOrders(sortvalue));
        }

        public async Task<IActionResult> Search(string search)
        {
            return PartialView("_OrdersPartial", await _orderService.Search(search));
        }


        [HttpGet]
        public async Task<IActionResult> CreateOrder()
        {
            if (!User.Identity.IsAuthenticated)
            {
                return RedirectToAction("Login", "Account");
            }

            OrderIndexVM orderIndexVM = await _orderService.GetOrderViewModel();

            if (orderIndexVM.Baskets.Count <= 0)
            {
                return RedirectToAction("Index", "Home");
            }

            return View(orderIndexVM);
        }

        [HttpPost]
        public async Task<IActionResult> CreateOrder(OrderCreateVM orderCreateVM)
        {
            if (!ModelState.IsValid)
            {
                ModelState.AddModelError("", "");
                TempData["error"] = "Error!";
                return RedirectToAction("CreateOrder");
            }

            await _orderService.CreateOrder(orderCreateVM);

            return RedirectToAction("Index", "Home");
        }


        [HttpPost]
        public async Task<IActionResult> CreateCard([FromBody] CardCreateVM cardCreateVM)
        {
            if (!ModelState.IsValid) return StatusCode(406);

            return PartialView("_CheckoutCurrentUserCardPartial", await _orderService.CreateCard(cardCreateVM));
        }

        [HttpPost]
        public async Task<IActionResult> CreateAddress([FromBody] AddressCreateVM addressCreateVM)
        {
            if (!ModelState.IsValid) return StatusCode(406);

            return PartialView("_CheckoutCurrentUserAddressPartial", await _orderService.CreateAddress(addressCreateVM));
        }

        [HttpPost]
        public async Task<IActionResult> UpdateUser([FromBody] AppUserUpdateVM appUserUpdateVM)
        {
            if (!ModelState.IsValid) return StatusCode(406);

            foreach (var item in await _orderService.UpdateUser(appUserUpdateVM))
            {
                ModelState.AddModelError("", item);

                return View("Index");
            }

            return StatusCode(200);
        }

        public async Task<IActionResult> DeleteFromBasket(DeleteFromBasketVM deleteFromBasketVM)
        {
            if (deleteFromBasketVM == null) return BadRequest();

            List<BasketVM> baskets = await _orderService.DeleteFromBasket(deleteFromBasketVM);

            return PartialView("_CheckoutBasketsPartial", baskets);
        }

        public async Task<IActionResult> GetBasket()
        {
            return PartialView("_CheckoutSubmitFormPartial", await _orderService.GetBasket());
        }
    }
}

Pull_Bear/Pull_Bear.MVC/Views/Order/CreateOrder.cshtml
@model OrderIndexVM

<main>
    <section class="whereareyou">
        <div class="where">.</div>
    </section>

    <div class="basketindex" style="opacity: 0; visibility: hidden;">.</div>

    <section class="breadcrumb">
        <div class="container">
            <div class="row keeper">
                <div class="col-lg-6">
                    <a asp-controller="Home" asp-action="Index">MAIN PAGE</a>&nbsp;/ <a asp-controller="Basket" asp-action="Index">BASKET</a>&nbsp;/ CHECKOUT
                </div>
            </div>
        </div>
    </section>

    <section class="checkoutsection">
        <div class="container">
            <div class="row all">
                <p class="firstp">CHECK OUT</p>

                @await Html.PartialAsync("_CheckoutFormPartial", Model.OrderCreateVM)

                <div class="rightcheckout col-lg-5 col-12">
                    @await Html.PartialAsync("_CheckoutSubmitFormPartial", Model.Baskets.Sum(x => x.Count * x.Price))
                </div>

                @await Html.PartialAsync("_CheckoutAddAccountInfoFormPartial", new AppUserUpdateVM())

                @await Html.PartialAsync("_CheckoutAddAddressFormPartial", new AddressCreateVM())

                @await Html.PartialAsync("_CheckoutAddCardFormPartial", new CardCreateVM())

                <div class="boughtorders col-lg-12 col-12">
                    @await Html.PartialAsync("_CheckoutBasketsPartial", Model.Baskets)
                </div>
            </div>
        </div>
    </section>

    <section class="cardmodal ">
        <div class="closekeeper ">
            <ion-icon name="close-circle-outline" class="closecardmodal"></ion-icon>
            <div class="container dontclose">
                <div class="row all">
                    <p class="firstp col-lg-12 col-12">MY CARDS</p>
                    <div class="carddiv carddivforfetch col-lg-12 col-12">
                        @await Html.PartialAsync("_CheckoutCurrentUserCardPartial", Model.AppUserGetVM.Cards)
                    </div>
                </div>
            </div>
        </div>
    </section>

    <section class="addressmodal">
        <div class="closekeeper">
            <ion-icon name="close-circle-outline" class="closeaddressmodal"></ion-icon>
            <div class="container dontclose">
                <div class="row all">
                    <p class="firstp col-lg-12 col-12">MY ADDRESSES</p>
                    <div class="addressdiv col-lg-12 col-12">
                        @await Html.PartialAsync("_CheckoutCurrentUserAddressPartial", Model.AppUserGetVM.Addresses)
                    </div>
                </div>
            </div>
        </div>
    </section>
</main>

Pull_Bear/Pull_Bear.MVC/Views/Order/Index.cshtml
@model List<OrderListVM>

<main>
    <section class="whereareyou">
        <div class="where">.</div>
    </section>

    <section class="breadcrumbregsiter">
        <div class="container">
            <div class="row keeper">
                <div class="col-lg-6">
                    <a asp-controller="Home" asp-action="Index">MAIN PAGE</a>&nbsp;/ PURCHASES
                </div>
            </div>
        </div>
    </section>

    <section class="ordersection">
        <div class="container">
            <div class="row all">
                <p class="firstp">PURCHASES</p>

                <div class="col-lg-4 col-10 ordersearchkeeper">
                    <input @*data-url="http://localhost:53427/Order/Search"*@ class="search_input_order" id="order_search" placeholder="SEARCH" type="text">
                    <a class="xz">
                        <ion-icon name="search-outline" class="search_icon_order"></ion-icon>
                    </a>
                </div>

                <ul class="head_categories col-12 col-lg-7">

                    <li class="headcategoryli ">
                        <a asp-controller="Order" asp-action="SortOrders" asp-route-sortvalue="All" class="categoryhref categoriesfororder">ALL</a>
                    </li>

                    @foreach (var item in Enum.GetNames(typeof(OrderStatus)))
                    {
                        <li class="headcategoryli ">
                            <a asp-controller="Order" asp-action="SortOrders" asp-route-sortvalue="@item" class="categoryhref categoriesfororder">@item.ToUpperInvariant()</a>
                        </li>
                    }
                </ul>
                <div class="orders col-lg-12 col-12">

                    @await Html.PartialAsync("_OrdersPartial", Model)

                </div>
            </div>
        </div>
    </section>
</main>