Pull_Bear/Pull_Bear.MVC/Controllers/AddressController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Pull_Bear.Service.Interfaces;
using Pull_Bear.Service.ViewModels.AddressVMs;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Pull_Bear.MVC.Controllers
{
    public class AddressController : Controller
    {
        private readonly IAddressService _addressService;
         
        public AddressController(IAddressService addressService)
        {
            _addressService = addressService;
        }

        [Authorize(Roles = "Member")]
        public async Task<IActionResult> Index()
        {
            AddressIndexVM addressIndexVM = new AddressIndexVM() { AddressCreateVM = new AddressCreateVM(), Addresses = await _addressService.GetAllAsync() };

            return View(addressIndexVM);
        }

        [Authorize(Roles = "Member")]
        public async Task<IActionResult> GetAddresses()
        {
            return PartialView("_CheckoutCurrentUserAddressPartial", await _addressService.GetAllAsync());
        }

        [Authorize(Roles = "Member")]
        [HttpPost]
        public async Task<IActionResult> CreateAddress([FromBody] AddressCreateVM addressCreateVM)
        {
            if (!ModelState.IsValid)
            {
                ModelState.AddModelError("", "");
                //return PartialView("_AddressListPartial", await _addressService.GetAllAsync());
                return StatusCode(406);
            }

            await _addressService.CreateAsync(addressCreateVM);
            return PartialView("_AddressListPartial", await _addressService.GetAllAsync());
        }

        [Authorize(Roles = "Member")]
        public async Task<IActionResult> DeleteAddress(int? id)
        {
            await _addressService.DeleteAsync(id);

            return PartialView("_AddressListPartial", await _addressService.GetAllAsync());
        }

        [Authorize(Roles = "Member")]
        public async Task<IActionResult> MakeMain(int? id)
        {
            await _addressService.MakeMain(id);

            return PartialView("_AddressListPartial", await _addressService.GetAllAsync());
        }

    }
}

Pull_Bear/Pull_Bear.MVC/Controllers/CardController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Pull_Bear.Service.Interfaces;
using Pull_Bear.Service.ViewModels.CardVMs;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Pull_Bear.MVC.Controllers
{
    public class CardController : Controller
    {
        private readonly ICardService _cardService;
         
        public CardController(ICardService cardService)
        {
            _cardService = cardService;
        }

        [Authorize(Roles = "Member")]
        public async Task<IActionResult> Index()
        {
            CardIndexVM cardIndexVM = new CardIndexVM() { CardCreateVM = new CardCreateVM(), Cards = await _cardService.GetAllAsync() };

            return View(cardIndexVM);
        }

        [Authorize(Roles = "Member")]
        public async Task<IActionResult> GetCards()
        {
            return PartialView("_CheckoutCurrentUserCardPartial", await _cardService.GetAllAsync());
        }

        [Authorize(Roles = "Member")]
        [HttpPost]
        public async Task<IActionResult> CreateCard([FromBody] CardCreateVM cardCreateVM)
        {
            if (!ModelState.IsValid)
            {
                ModelState.AddModelError("", "");
                //return PartialView("_CardListPartial", await _cardService.GetAllAsync());
                return StatusCode(406);
            }

            await _cardService.CreateAsync(cardCreateVM);
            return PartialView("_CardListPartial", await _cardService.GetAllAsync());
        }

        [Authorize(Roles = "Member")]
        public async Task<IActionResult> DeleteCard(int? id)
        {
            await _cardService.DeleteAsync(id);

            return PartialView("_CardListPartial", await _cardService.GetAllAsync());
        }

        [Authorize(Roles = "Member")]
        public async Task<IActionResult> MakeMain(int? id)
        {
            await _cardService.MakeMain(id);

            return PartialView("_CardListPartial", await _cardService.GetAllAsync());
        }
    }
}

Pull_Bear/Pull_Bear.MVC/Controllers/OrderController.cs
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Pull_Bear.Service.Interfaces;
using Pull_Bear.Service.ViewModels.AddressVMs;
using Pull_Bear.Service.ViewModels.AppUserVMs;
using Pull_Bear.Service.ViewModels.BasketVMs;
using Pull_Bear.Service.ViewModels.CardVMs;
using Pull_Bear.Service.ViewModels.OrderVMs;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;

namespace Pull_Bear.MVC.Controllers
{
    public class OrderController : Controller
    {
        private readonly IOrderService _orderService;
        private readonly IMapper _mapper; 

        public OrderController(IOrderService orderService, IMapper mapper)
        {
            _orderService = orderService;
            _mapper = mapper;
        }

        [Authorize(Roles = "Member")]
        public async Task<IActionResult> Index()
        {
            return View(await _orderService.GetOrders());
        }

        public async Task<IActionResult> SortOrders(string sortvalue)
        {
            return PartialView("_OrdersPartial", await _orderService.SortOrders(sortvalue));
        }

        public async Task<IActionResult> Search(string search)
        {
            return PartialView("_OrdersPartial", await _orderService.Search(search));
        }


        [HttpGet]
        public async Task<IActionResult> CreateOrder()
        {
            if (!User.Identity.IsAuthenticated)
            {
                return RedirectToAction("Login", "Account");
            }

            OrderIndexVM orderIndexVM = await _orderService.GetOrderViewModel();

            if (orderIndexVM.Baskets.Count <= 0)
            {
                return RedirectToAction("Index", "Home");
            }

            return View(orderIndexVM);
        }

        [HttpPost]
        public async Task<IActionResult> CreateOrder(OrderCreateVM orderCreateVM)
        {
            if (!ModelState.IsValid)
            {
                ModelState.AddModelError("", "");
                TempData["error"] = "Error!";
                return RedirectToAction("CreateOrder");
            }

            await _orderService.CreateOrder(orderCreateVM);

            return RedirectToAction("Index", "Home");
        }


        [HttpPost]
        public async Task<IActionResult> CreateCard([FromBody] CardCreateVM cardCreateVM)
        {
            if (!ModelState.IsValid) return StatusCode(406);

            return PartialView("_CheckoutCurrentUserCardPartial", await _orderService.CreateCard(cardCreateVM));
        }

        [HttpPost]
        public async Task<IActionResult> CreateAddress([FromBody] AddressCreateVM addressCreateVM)
        {
            if (!ModelState.IsValid) return StatusCode(406);

            return PartialView("_CheckoutCurrentUserAddressPartial", await _orderService.CreateAddress(addressCreateVM));
        }

        [HttpPost]
        public async Task<IActionResult> UpdateUser([FromBody] AppUserUpdateVM appUserUpdateVM)
        {
            if (!ModelState.IsValid) return StatusCode(406);

            foreach (var item in await _orderService.UpdateUser(appUserUpdateVM))
            {
                ModelState.AddModelError("", item);

                return View("Index");
            }

            return StatusCode(200);
        }

        public async Task<IActionResult> DeleteFromBasket(DeleteFromBasketVM deleteFromBasketVM)
        {
            if (deleteFromBasketVM == null) return BadRequest();

            List<BasketVM> baskets = await _orderService.DeleteFromBasket(deleteFromBasketVM);

            return PartialView("_CheckoutBasketsPartial", baskets);
        }

        public async Task<IActionResult> GetBasket()
        {
            return PartialView("_CheckoutSubmitFormPartial", await _orderService.GetBasket());
        }
    }
}

Pull_Bear/Pull_Bear.MVC/Controllers/ShopController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Pull_Bear.Service.Interfaces;
using Pull_Bear.Service.ViewModels;
using Pull_Bear.Service.ViewModels.ProductColorSizeVMs;
using Pull_Bear.Service.ViewModels.ProductReviewVMs;
using Pull_Bear.Service.ViewModels.ProductVMs;
using Pull_Bear.Service.ViewModels.SortVMs;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Pull_Bear.MVC.Controllers
{
    public class ShopController : Controller
    {
        private readonly IShopService _shopService; 
        public ShopController(IShopService shopService)
        {
            _shopService = shopService;
        }

        public async Task<IActionResult> Index(int genderId, int parentcategoryid)
        {
            return View(await _shopService.GetDataAsync(genderId, parentcategoryid));
        }

        public async Task<IActionResult> CreateSort([FromBody] SortVM sortVM)
        {
            IQueryable<ProductListVM> products = await _shopService.CreateSort(sortVM);

            var a = PaginationList<ProductListVM>.Create(products, sortVM.Page == 0 ? 1 : sortVM.Page, sortVM.SelectValue == 0 ? 6 : sortVM.SelectValue);

            return PartialView("_ProductIndexPartial", a);
        }

        public async Task<IActionResult> ProductDetail(int? id)
        {
            if (id == null) return BadRequest();

            ViewBag.ProductId = id;

            return View(await _shopService.GetProduct(id));
        }

        [Authorize(Roles = ("Member"))]
        public async Task<IActionResult> AddReview(WriteReviewVM writeReviewVM, int? id)
        {
            if (!ModelState.IsValid)
            {
                ModelState.AddModelError("", "");
                TempData["error"] = "Error!";
                return PartialView("_ProductReviewPartial", await _shopService.AddReview(writeReviewVM, id));
            }

            ViewBag.ProductId = id;
            TempData["success"] = "Thanks for review!";
            return PartialView("_ProductReviewPartial", await _shopService.AddReview(writeReviewVM, id));
        }

        public async Task<IActionResult> Search(string search)
        {
            var a = await _shopService.Search(search);

            return PartialView("_SearchPartial", a);
        }

        public async Task<IActionResult> GetReviewCount(int? id)
        {
            return PartialView("_ReviewCountPartial", await _shopService.GetReviewCount(id));
        }

        [Authorize(Roles = ("Member"))]
        public async Task<IActionResult> Like(int? id)
        {
            return Json(await _shopService.Like(id));
        }
    }
}

Pull_Bear/Pull_Bear.MVC/Views/Shared/_AddressListPartial.cshtml
@model List<AddressListVM>

@foreach (var item in Model)
{
    <div class="addressinozu col-lg-4 col-12">
        <div class="addressozu col-lg-12 col-12">

            <div class="top">
                <span class="cityname col-lg-12 col-12">
                    City: @item.City.ToUpperInvariant()
                </span>
                <span class="countryname col-lg-12 col-12">
                    Country: @item.Country.ToUpperInvariant()
                </span>
            </div>
            <div class="bottom">
                <span class="address1name col-lg-12 col-12">
                    <span class="col-lg-12 col-12">
                        Address1:
                    </span>
                    <span class="col-lg-12">
                        @item.Address1
                    </span>
                </span>
                <span class="address2name col-lg-12 col-12">
                    <span class="col-lg-12 col-12">
                        Address2:
                    </span>
                    <span class="col-lg-12 col-12">
                        @item.Address2
                    </span>
                </span>
                <span class="zipcodename col-lg-12 col-12">
                    <span class="col-lg-12 col-12">
                        ZIP code:
                    </span>
                    <span class="col-lg-12 col-12">
                        @item.ZipCode
                    </span>
                </span>
            </div>
            <span class="deleteaddress">
                <a asp-controller="Address" asp-action="DeleteAddress" asp-route-id="@item.Id" class="deleteusersaddress">
                    <svg width="24" height="24" viewBox="0 0 24 24" fill="none"
                         xmlns="http://www.w3.org/2000/svg">
                        <path d="M3.75 4.2998V22.9998H20.25V4.2998H3.75Z" stroke="black"
                              stroke-linejoin="round" />
                        <path d="M9.8 9.7998V16.9498M14.2 9.7998V16.9498M1 4.2998H23" stroke="black"
                              stroke-linecap="round" stroke-linejoin="round" />
                        <path d="M7.60059 4.3L9.40954 1H14.6279L16.4006 4.3H7.60059Z" stroke="black"
                              stroke-linejoin="round" />
                    </svg>
                </a>
            </span>

            @if (item.IsMain)
            {
                <span class=" ismain">Main Address</span>
            }
            else
            {
                <span class="makemain">
                    <a asp-controller="Address" asp-action="MakeMain" class="makeaddressmain" asp-route-id="@item.Id">
                        MAKE MAIN
                    </a>
                </span>
            }
        </div>
    </div>
}

Pull_Bear/Pull_Bear.MVC/Views/Shared/_BasketPartial.cshtml
@model List<BasketVM>

<a class="openbasket baskethref forclosebasket" asp-controller="Basket" asp-action="Index">
    <svg class="forclosebasket" width="26" height="31" viewBox="0 0 28 34" fill="none"
         xmlns="http://www.w3.org/2000/svg">
        <path class="cart_path"
              d="M2.73753 7.0387L2.24128 7.10005L2.24071 7.095L2.73753 7.0387ZM25.539 21.8904L26.0353 21.9518L25.539 21.8904ZM27.1671 8.72275L27.6633 8.7841L27.1671 8.72275ZM4.07752 21.9518L2.2413 7.10005L3.23375 6.97735L5.06996 21.8291L4.07752 21.9518ZM27.6633 8.7841L26.0353 21.9518L25.0428 21.8291L26.6708 8.6614L27.6633 8.7841ZM23.5542 24.145L6.55863 24.145V23.145L23.5542 23.145V24.145ZM25.6784 7.5387L2.73753 7.5387V6.5387L25.6784 6.5387L25.6784 7.5387ZM2.24071 7.095L1.75747 2.83112L2.75111 2.71851L3.23435 6.98239L2.24071 7.095ZM0.267008 1.50004H0L0 0.500036H0.267008L0.267008 1.50004ZM1.75747 2.83112C1.67154 2.0729 1.03007 1.50004 0.267008 1.50004L0.267008 0.500036C1.53879 0.500036 2.60789 1.45482 2.75111 2.71851L1.75747 2.83112ZM26.0353 21.9518C25.8804 23.2043 24.8162 24.145 23.5542 24.145V23.145C24.3114 23.145 24.9499 22.5806 25.0428 21.8291L26.0353 21.9518ZM26.6708 8.6614C26.7446 8.06498 26.2793 7.5387 25.6784 7.5387L25.6784 6.5387C26.8803 6.5387 27.8108 7.59127 27.6633 8.7841L26.6708 8.6614ZM5.06996 21.8291C5.16288 22.5806 5.80137 23.145 6.55863 23.145V24.145C5.29654 24.145 4.23238 23.2043 4.07752 21.9518L5.06996 21.8291Z"
              fill="#FFFFFF" />
        <path class="cart_path"
              d="M10.0856 30.9237C10.0856 29.5837 9.11799 28.4974 7.92439 28.4974C6.73079 28.4974 5.76318 29.5837 5.76318 30.9237C5.76318 32.2637 6.73079 33.3499 7.92439 33.3499C9.11799 33.3499 10.0856 32.2637 10.0856 30.9237Z"
              stroke="#FFFFFF" />
        <path class="cart_path"
              d="M24.4938 30.9237C24.4938 29.5837 23.5262 28.4974 22.3326 28.4974C21.139 28.4974 20.1714 29.5837 20.1714 30.9237C20.1714 32.2637 21.139 33.3499 22.3326 33.3499C23.5262 33.3499 24.4938 32.2637 24.4938 30.9237Z"
              stroke="#FFFFFF" />
    </svg>
    <span class="forclosebasket bskcount">@Model.Count</span>
</a>
<div class="minibasket forclosebasket">
    <div class="basket_count forclosebasket">BASKET (<span class="bskcount">@Model.Count</span>)</div>

    @if (Model == null || Model.Count <= 0)
    {
        <div class="ifbasketisempty forclosebasket">
            <div class="allforp forclosebasket">
                <p class="col-lg-10 col-10 p-0 forclosebasket">
                    <span class="forclosebasket">Oops!</span> Looks like you haven't added anything to your Cart!
                </p>
            </div>
        </div>
    }
    else
    {
        <div class="basket_items forclosebasket ">
            @foreach (BasketVM item in Model)
            {
                <div class="basket_item forclosebasket">

                    <div class="col-lg-2-5 col-3 left forclosebasket">
                        <a asp-controller="Shop" asp-action="ProductDetail" asp-route-id="@item.ProductId">
                            <img class="img-fluid" src="~/assets/images/products/@item.ProductId/@item.ProductImage" alt="">
                        </a>
                    </div>

                    <div class="col-lg-9 col-9 right forclosebasket">
                        <ul class="forclosebasket">
                            <li class="forclosebasket">
                                <span>@item.Name.ToUpperInvariant()</span>
                                <span class="price col-lg-3 col-3">@item.Price $</span>
                            </li>
                            <li class="forclosebasket">
                                <span>AMOUNT:</span>
                                <span class="item_amount"> @item.Count</span>
                            </li>
                            <li class="forclosebasket">
                                <span>SIZE:</span>
                                <span class="item_size">@item.SizeName</span>
                            </li>
                            <li class="forclosebasket">
                                <span>COLOR:</span>
                                <span class="item_size" style="color: @item.ColorHexCode;">@item.ColorName</span>
                            </li>
                            <li class="forclosebasket">
                                <span>TOTAL:</span>
                                <span class="amount_price">@item.Count x @item.Price $</span>
                                <span class="totalpriceproduct">@(item.Count * item.Price) $</span>
                            </li>
                        </ul>

                        <a asp-controller="Basket" asp-action="DeleteFromBasket" asp-route-productid="@item.ProductId" asp-route-colorid="@item.ColorId" asp-route-sizeid="@item.SizeId" asp-route-countinbasket="@item.Count" class="forclosebasket deletefrombasket classforbasketscssdelete">
                            <svg class="forclosebasket" width="24" height="24" viewBox="0 0 24 24" fill="none"
                                 xmlns="http://www.w3.org/2000/svg">
                                <path class="forclosebasket" d="M3.75 4.3V23H20.25V4.3H3.75Z" stroke="black"
                                      stroke-linejoin="round" />
                                <path class="forclosebasket" d="M9.8 9.8V16.95M14.2 9.8V16.95M1 4.3H23" stroke="black"
                                      stroke-linecap="round" stroke-linejoin="round" />
                                <path class="forclosebasket" d="M7.60034 4.3L9.40929 1H14.6277L16.4003 4.3H7.60034Z" stroke="black"
                                      stroke-linejoin="round" />
                            </svg>
                        </a>
                    </div>
                </div>
            }
        </div>
    }
    <div class="basketbottombtns forclosebasket ">
        <div class="top forclosebasket">
            <div class="left forclosebasket">
                <div class="lefttop forclosebasket">
                    TOTAL:
                </div>
                <div class="leftbottom forclosebasket">
                    DELIVERY:
                </div>
            </div>
            <div class="right forclosebasket">
                <div class="righttop forclosebasket">
                    @(Model.Sum(x=>x.Price * x.Count)) $
                </div>
                <div class="rightbottom forclosebasket">
                    FREE
                </div>
            </div>
        </div>
        <div class="bottom forclosebasket">
            <div class="left forclosebasket">
                <a asp-controller="Basket" asp-action="Index">GO TO CART</a>
            </div>
            <div class="right forclosebasket">
                <a asp-controller="Order" asp-action="CreateOrder">CHECKOUT</a>
            </div>
        </div>
    </div>
</div>

Pull_Bear/Pull_Bear.MVC/Views/Shared/_CardListPartial.cshtml
@model List<CardListVM>

@foreach (CardListVM card in Model)
{
    <div class="cardinozu col-lg-4 col-12">
        <div class="cardozu col-lg-12 col-12">
            <span class="col-lg-1-5 col-1-5">
                <img class="img-fluid" src="~/assets/images/settings/mastercard.jpg" alt="">
            </span>
            <span class="cardno">
                @for (int i = 0; i <= 6; i++)
                {
                    if (i == 4)
                    {
                        @(" ")
                    }

                    @card.CardNo.ToString()[i]
                }
                @for (int i = 7; i < card.CardNo.ToString().Length; i++)
                {
                    @("*")
                }
            </span>
            <span class="cardexpire">
                @card.ExpireDate
            </span>
            <span class="cardholder">
                @card.CardHolder
            </span>
            <span class="deletecard">
                <a asp-controller="Card" asp-action="DeleteCard" asp-route-id="@card.Id" class="deleteuserscard">
                    <svg width="24" height="24" viewBox="0 0 24 24" fill="none"
                         xmlns="http://www.w3.org/2000/svg">
                        <path d="M3.75 4.2998V22.9998H20.25V4.2998H3.75Z" stroke="black"
                              stroke-linejoin="round" />
                        <path d="M9.8 9.7998V16.9498M14.2 9.7998V16.9498M1 4.2998H23" stroke="black"
                              stroke-linecap="round" stroke-linejoin="round" />
                        <path d="M7.60059 4.3L9.40954 1H14.6279L16.4006 4.3H7.60059Z" stroke="black"
                              stroke-linejoin="round" />
                    </svg>
                </a>
            </span>
            @if (card.IsMain)
            {
                <span class="ismain">Main Card</span>
            }
            else
            {
                <span class="makemain">
                    <a asp-controller="Card" asp-action="MakeMain" asp-route-id="@card.Id" class="makemaincard">
                        MAKE MAIN
                    </a>
                </span>
            }
            <span class=" headword">International card</span>
        </div>
    </div>
}

Pull_Bear/Pull_Bear.MVC/Views/Shared/_CheckoutAddAddressFormPartial.cshtml
@model AddressCreateVM

<div class="formaddresskeeper formkeeper col-lg-5 col-12">
    <span class="closeform">
        <ion-icon name="close-circle-outline"></ion-icon>
    </span>

    <div asp-validation-summary="ModelOnly" class="text text-danger"></div>
    <form id="changeaddressform" method="post" class="col-lg-12 col-12 changeaddressform" asp-controller="Order" asp-action="CreateAddress">
        <label asp-for="Address1" for="address1"><span>*</span>ADDRESS 1</label>
        <input asp-for="Address1" name="address1" class="col-12 col-lg-12" id="address1" required>

        <label asp-for="Address2" for="address2"><span>*</span>ADDRESS 2</label>
        <input asp-for="Address2" name="address2" class="col-12 col-lg-12" id="address2">

        <label asp-for="Country" for="country"><span>*</span> COUNTRY</label>
        <input asp-for="Country" name="country" id="country" class="col-12 col-lg-12" required>

        <div class="checkoutcity col-6 col-lg-6">
            <label asp-for="City" for="city"><span>*</span> CITY</label>
            <input asp-for="City" name="city" id="city" class="col-12 col-lg-12" required>
        </div>

        <div class="checkoutcountry col-6 col-lg-6">
            <label asp-for="ZipCode" for="zipcode"><span>*</span> ZIP CODE</label>
            <input asp-for="ZipCode" name="zipcode" id="zipcode" class="col-12 col-lg-12" required
                   max="10" maxlength="10" title="ZIP code must be at most 10 characters!">
        </div>

        <div class="checkoutcity col-5-8 col-lg-5-8">
            <button form="changeaddressform" type="submit" class="addresschangebtn " value="save">SAVE</button>
        </div>

        <div class="checkoutcity col-5-8 col-lg-5-8">
            <button form="changeaddressform" type="submit" class="addresschangebtn " value="dontsave">DON'T SAVE</button>
        </div>
    </form>
</div>

Pull_Bear/Pull_Bear.MVC/Views/Shared/_CheckoutBasketsPartial.cshtml
@model List<BasketVM>

    <p class="orderdet col-lg-12 col-12">
        ORDER DETAILS
    </p>

    @foreach (BasketVM basket in Model)
    {
        <div class="col-lg-2-5 checkoutbasketitem col-3">
            <a asp-controller="Shop" asp-action="ProductDetail" asp-route-id="@basket.ProductId" class="proddet">
                <img class="img-fluid" src="~/assets/images/products/@basket.ProductId/@basket.Product.ProductImage" alt="">
            </a>
            <a asp-controller="Order" asp-action="DeleteFromBasket" asp-route-productid="@basket.ProductId" asp-route-colorid="@basket.ColorId" asp-route-sizeid="@basket.SizeId" class="deletebasketelementfromcheckout">
                <svg width="20" height="20" viewBox="0 0 20 20" fill="none"
                     xmlns="http://www.w3.org/2000/svg">
                    <path d="M3.25 3.69995V19H16.75V3.69995H3.25Z" stroke="black"
                          stroke-linejoin="round" />
                    <path d="M8.2 8.19995V14.05M11.8 8.19995V14.05M1 3.69995H19" stroke="black"
                          stroke-linecap="round" stroke-linejoin="round" />
                    <path d="M6.40039 3.7L7.88044 1H12.15L13.6004 3.7H6.40039Z" stroke="black"
                          stroke-linejoin="round" />
                </svg>
            </a>
        </div>
    }

Pull_Bear/Pull_Bear.MVC/Views/Shared/_CreateAddressFormPartial.cshtml
@model AddressCreateVM

<div class="addressform col-lg-4 col-12">

    <p class="clicktoaddnewaddress">
        ADD NEW
    </p>

    <div class="again_allcontent">
        <div class="allcontent col-lg-12 col-12">
            <div asp-validation-summary="ModelOnly" class="text text-danger"></div>
            <form method="post" id="addnewaddressform" enctype="multipart/form-data"
                  class="addressozu col-lg-12 col-12 addnewaddressform" asp-controller="Address" asp-action="CreateAddress">

                <input asp-for="Address1" name="address1" class="col-12 col-lg-12 addressaddress1"
                       id="addressaddress1" type="text" required placeholder="ADDRESS 1">

                <input asp-for="Address2" name="address2" class="col-12 col-lg-12 addressaddress2"
                       id="addressaddress2" type="text" placeholder="ADDRESS 2">

                <input asp-for="Country" name="country" id="addresscountry"
                       class="col-12 col-lg-12 addresscountry" type="text" required
                       placeholder="COUNTRY">

                <input asp-for="City" name="city" id="addresscity" class="col-12 col-lg-12 addresscity"
                       type="text" required placeholder="CITY">

                <input asp-for="ZipCode" name="zipcode" id="addresszipcode"
                       class="col-12 col-lg-12 addresszipcode" type="text" required max="10"
                       maxlength="10" title="ZIP code must be at most 10 characters!"
                       placeholder="ZIP code">

                <button form="addnewaddressform" type="submit"
                        class="addresschangebtn col-lg-2-5 col-2-5" value="save">
                    SAVE
                </button>

                <button type="button" class="cancelnewaddress col-lg-2-5 col-2-5"
                        value="save">
                    CANCEL
                </button>

                <button form="addnewaddressform" type="submit"
                        class="addresschangebtn col-lg-6-5 col-6-5" value="add">
                    SAVE AND MAKE MAIN
                </button>
            </form>
        </div>
    </div>
</div>

@section Script{
    <partial name="_ValidationPartial">
}